version: '3.7'

services:
  server:
    image: portal_backend_image
    container_name: portal_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV="development"
      - MONGO_URL=mongodb://mongo:27017
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    image: portal_frontend_image
    container_name: portal_frontend
    command: npm start
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://192.168.0.115:3000/api/v1
    ports:
      - "3003:3003"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local